// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flare/rpc/protocol/protobuf/binlog.proto

#ifndef PROTOBUF_flare_2frpc_2fprotocol_2fprotobuf_2fbinlog_2eproto__INCLUDED
#define PROTOBUF_flare_2frpc_2fprotocol_2fprotobuf_2fbinlog_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace flare {
namespace rpc {
class SerializedClientPacket;
class SerializedClientPacketDefaultTypeInternal;
extern SerializedClientPacketDefaultTypeInternal _SerializedClientPacket_default_instance_;
class SerializedServerPacket;
class SerializedServerPacketDefaultTypeInternal;
extern SerializedServerPacketDefaultTypeInternal _SerializedServerPacket_default_instance_;
}  // namespace rpc
}  // namespace flare

namespace flare {
namespace rpc {

namespace protobuf_flare_2frpc_2fprotocol_2fprotobuf_2fbinlog_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_flare_2frpc_2fprotocol_2fprotobuf_2fbinlog_2eproto

// ===================================================================

class SerializedClientPacket : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:flare.rpc.SerializedClientPacket) */ {
 public:
  SerializedClientPacket();
  virtual ~SerializedClientPacket();

  SerializedClientPacket(const SerializedClientPacket& from);

  inline SerializedClientPacket& operator=(const SerializedClientPacket& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SerializedClientPacket(SerializedClientPacket&& from) noexcept
    : SerializedClientPacket() {
    *this = ::std::move(from);
  }

  inline SerializedClientPacket& operator=(SerializedClientPacket&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SerializedClientPacket& default_instance();

  static inline const SerializedClientPacket* internal_default_instance() {
    return reinterpret_cast<const SerializedClientPacket*>(
               &_SerializedClientPacket_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SerializedClientPacket* other);
  friend void swap(SerializedClientPacket& a, SerializedClientPacket& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SerializedClientPacket* New() const PROTOBUF_FINAL { return New(NULL); }

  SerializedClientPacket* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SerializedClientPacket& from);
  void MergeFrom(const SerializedClientPacket& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SerializedClientPacket* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes body = 3;
  void clear_body();
  static const int kBodyFieldNumber = 3;
  const ::std::string& body() const;
  void set_body(const ::std::string& value);
  #if LANG_CXX11
  void set_body(::std::string&& value);
  #endif
  void set_body(const char* value);
  void set_body(const void* value, size_t size);
  ::std::string* mutable_body();
  ::std::string* release_body();
  void set_allocated_body(::std::string* body);

  // bytes attachment = 4;
  void clear_attachment();
  static const int kAttachmentFieldNumber = 4;
  const ::std::string& attachment() const;
  void set_attachment(const ::std::string& value);
  #if LANG_CXX11
  void set_attachment(::std::string&& value);
  #endif
  void set_attachment(const char* value);
  void set_attachment(const void* value, size_t size);
  ::std::string* mutable_attachment();
  ::std::string* release_attachment();
  void set_allocated_attachment(::std::string* attachment);

  // int32 status = 1;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // bool streaming_rpc = 2;
  void clear_streaming_rpc();
  static const int kStreamingRpcFieldNumber = 2;
  bool streaming_rpc() const;
  void set_streaming_rpc(bool value);

  // bool using_raw_bytes = 5;
  void clear_using_raw_bytes();
  static const int kUsingRawBytesFieldNumber = 5;
  bool using_raw_bytes() const;
  void set_using_raw_bytes(bool value);

  // @@protoc_insertion_point(class_scope:flare.rpc.SerializedClientPacket)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr body_;
  ::google::protobuf::internal::ArenaStringPtr attachment_;
  ::google::protobuf::int32 status_;
  bool streaming_rpc_;
  bool using_raw_bytes_;
  mutable int _cached_size_;
  friend struct protobuf_flare_2frpc_2fprotocol_2fprotobuf_2fbinlog_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SerializedServerPacket : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:flare.rpc.SerializedServerPacket) */ {
 public:
  SerializedServerPacket();
  virtual ~SerializedServerPacket();

  SerializedServerPacket(const SerializedServerPacket& from);

  inline SerializedServerPacket& operator=(const SerializedServerPacket& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SerializedServerPacket(SerializedServerPacket&& from) noexcept
    : SerializedServerPacket() {
    *this = ::std::move(from);
  }

  inline SerializedServerPacket& operator=(SerializedServerPacket&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SerializedServerPacket& default_instance();

  static inline const SerializedServerPacket* internal_default_instance() {
    return reinterpret_cast<const SerializedServerPacket*>(
               &_SerializedServerPacket_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(SerializedServerPacket* other);
  friend void swap(SerializedServerPacket& a, SerializedServerPacket& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SerializedServerPacket* New() const PROTOBUF_FINAL { return New(NULL); }

  SerializedServerPacket* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SerializedServerPacket& from);
  void MergeFrom(const SerializedServerPacket& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SerializedServerPacket* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string method = 1;
  void clear_method();
  static const int kMethodFieldNumber = 1;
  const ::std::string& method() const;
  void set_method(const ::std::string& value);
  #if LANG_CXX11
  void set_method(::std::string&& value);
  #endif
  void set_method(const char* value);
  void set_method(const char* value, size_t size);
  ::std::string* mutable_method();
  ::std::string* release_method();
  void set_allocated_method(::std::string* method);

  // bytes body = 3;
  void clear_body();
  static const int kBodyFieldNumber = 3;
  const ::std::string& body() const;
  void set_body(const ::std::string& value);
  #if LANG_CXX11
  void set_body(::std::string&& value);
  #endif
  void set_body(const char* value);
  void set_body(const void* value, size_t size);
  ::std::string* mutable_body();
  ::std::string* release_body();
  void set_allocated_body(::std::string* body);

  // bytes attachment = 4;
  void clear_attachment();
  static const int kAttachmentFieldNumber = 4;
  const ::std::string& attachment() const;
  void set_attachment(const ::std::string& value);
  #if LANG_CXX11
  void set_attachment(::std::string&& value);
  #endif
  void set_attachment(const char* value);
  void set_attachment(const void* value, size_t size);
  ::std::string* mutable_attachment();
  ::std::string* release_attachment();
  void set_allocated_attachment(::std::string* attachment);

  // bool streaming_rpc = 2;
  void clear_streaming_rpc();
  static const int kStreamingRpcFieldNumber = 2;
  bool streaming_rpc() const;
  void set_streaming_rpc(bool value);

  // bool using_raw_bytes = 5;
  void clear_using_raw_bytes();
  static const int kUsingRawBytesFieldNumber = 5;
  bool using_raw_bytes() const;
  void set_using_raw_bytes(bool value);

  // @@protoc_insertion_point(class_scope:flare.rpc.SerializedServerPacket)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr method_;
  ::google::protobuf::internal::ArenaStringPtr body_;
  ::google::protobuf::internal::ArenaStringPtr attachment_;
  bool streaming_rpc_;
  bool using_raw_bytes_;
  mutable int _cached_size_;
  friend struct protobuf_flare_2frpc_2fprotocol_2fprotobuf_2fbinlog_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SerializedClientPacket

// int32 status = 1;
inline void SerializedClientPacket::clear_status() {
  status_ = 0;
}
inline ::google::protobuf::int32 SerializedClientPacket::status() const {
  // @@protoc_insertion_point(field_get:flare.rpc.SerializedClientPacket.status)
  return status_;
}
inline void SerializedClientPacket::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:flare.rpc.SerializedClientPacket.status)
}

// bool streaming_rpc = 2;
inline void SerializedClientPacket::clear_streaming_rpc() {
  streaming_rpc_ = false;
}
inline bool SerializedClientPacket::streaming_rpc() const {
  // @@protoc_insertion_point(field_get:flare.rpc.SerializedClientPacket.streaming_rpc)
  return streaming_rpc_;
}
inline void SerializedClientPacket::set_streaming_rpc(bool value) {
  
  streaming_rpc_ = value;
  // @@protoc_insertion_point(field_set:flare.rpc.SerializedClientPacket.streaming_rpc)
}

// bool using_raw_bytes = 5;
inline void SerializedClientPacket::clear_using_raw_bytes() {
  using_raw_bytes_ = false;
}
inline bool SerializedClientPacket::using_raw_bytes() const {
  // @@protoc_insertion_point(field_get:flare.rpc.SerializedClientPacket.using_raw_bytes)
  return using_raw_bytes_;
}
inline void SerializedClientPacket::set_using_raw_bytes(bool value) {
  
  using_raw_bytes_ = value;
  // @@protoc_insertion_point(field_set:flare.rpc.SerializedClientPacket.using_raw_bytes)
}

// bytes body = 3;
inline void SerializedClientPacket::clear_body() {
  body_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SerializedClientPacket::body() const {
  // @@protoc_insertion_point(field_get:flare.rpc.SerializedClientPacket.body)
  return body_.GetNoArena();
}
inline void SerializedClientPacket::set_body(const ::std::string& value) {
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:flare.rpc.SerializedClientPacket.body)
}
#if LANG_CXX11
inline void SerializedClientPacket::set_body(::std::string&& value) {
  
  body_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:flare.rpc.SerializedClientPacket.body)
}
#endif
inline void SerializedClientPacket::set_body(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:flare.rpc.SerializedClientPacket.body)
}
inline void SerializedClientPacket::set_body(const void* value, size_t size) {
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:flare.rpc.SerializedClientPacket.body)
}
inline ::std::string* SerializedClientPacket::mutable_body() {
  
  // @@protoc_insertion_point(field_mutable:flare.rpc.SerializedClientPacket.body)
  return body_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SerializedClientPacket::release_body() {
  // @@protoc_insertion_point(field_release:flare.rpc.SerializedClientPacket.body)
  
  return body_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SerializedClientPacket::set_allocated_body(::std::string* body) {
  if (body != NULL) {
    
  } else {
    
  }
  body_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), body);
  // @@protoc_insertion_point(field_set_allocated:flare.rpc.SerializedClientPacket.body)
}

// bytes attachment = 4;
inline void SerializedClientPacket::clear_attachment() {
  attachment_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SerializedClientPacket::attachment() const {
  // @@protoc_insertion_point(field_get:flare.rpc.SerializedClientPacket.attachment)
  return attachment_.GetNoArena();
}
inline void SerializedClientPacket::set_attachment(const ::std::string& value) {
  
  attachment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:flare.rpc.SerializedClientPacket.attachment)
}
#if LANG_CXX11
inline void SerializedClientPacket::set_attachment(::std::string&& value) {
  
  attachment_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:flare.rpc.SerializedClientPacket.attachment)
}
#endif
inline void SerializedClientPacket::set_attachment(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  attachment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:flare.rpc.SerializedClientPacket.attachment)
}
inline void SerializedClientPacket::set_attachment(const void* value, size_t size) {
  
  attachment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:flare.rpc.SerializedClientPacket.attachment)
}
inline ::std::string* SerializedClientPacket::mutable_attachment() {
  
  // @@protoc_insertion_point(field_mutable:flare.rpc.SerializedClientPacket.attachment)
  return attachment_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SerializedClientPacket::release_attachment() {
  // @@protoc_insertion_point(field_release:flare.rpc.SerializedClientPacket.attachment)
  
  return attachment_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SerializedClientPacket::set_allocated_attachment(::std::string* attachment) {
  if (attachment != NULL) {
    
  } else {
    
  }
  attachment_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), attachment);
  // @@protoc_insertion_point(field_set_allocated:flare.rpc.SerializedClientPacket.attachment)
}

// -------------------------------------------------------------------

// SerializedServerPacket

// string method = 1;
inline void SerializedServerPacket::clear_method() {
  method_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SerializedServerPacket::method() const {
  // @@protoc_insertion_point(field_get:flare.rpc.SerializedServerPacket.method)
  return method_.GetNoArena();
}
inline void SerializedServerPacket::set_method(const ::std::string& value) {
  
  method_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:flare.rpc.SerializedServerPacket.method)
}
#if LANG_CXX11
inline void SerializedServerPacket::set_method(::std::string&& value) {
  
  method_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:flare.rpc.SerializedServerPacket.method)
}
#endif
inline void SerializedServerPacket::set_method(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  method_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:flare.rpc.SerializedServerPacket.method)
}
inline void SerializedServerPacket::set_method(const char* value, size_t size) {
  
  method_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:flare.rpc.SerializedServerPacket.method)
}
inline ::std::string* SerializedServerPacket::mutable_method() {
  
  // @@protoc_insertion_point(field_mutable:flare.rpc.SerializedServerPacket.method)
  return method_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SerializedServerPacket::release_method() {
  // @@protoc_insertion_point(field_release:flare.rpc.SerializedServerPacket.method)
  
  return method_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SerializedServerPacket::set_allocated_method(::std::string* method) {
  if (method != NULL) {
    
  } else {
    
  }
  method_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), method);
  // @@protoc_insertion_point(field_set_allocated:flare.rpc.SerializedServerPacket.method)
}

// bool streaming_rpc = 2;
inline void SerializedServerPacket::clear_streaming_rpc() {
  streaming_rpc_ = false;
}
inline bool SerializedServerPacket::streaming_rpc() const {
  // @@protoc_insertion_point(field_get:flare.rpc.SerializedServerPacket.streaming_rpc)
  return streaming_rpc_;
}
inline void SerializedServerPacket::set_streaming_rpc(bool value) {
  
  streaming_rpc_ = value;
  // @@protoc_insertion_point(field_set:flare.rpc.SerializedServerPacket.streaming_rpc)
}

// bool using_raw_bytes = 5;
inline void SerializedServerPacket::clear_using_raw_bytes() {
  using_raw_bytes_ = false;
}
inline bool SerializedServerPacket::using_raw_bytes() const {
  // @@protoc_insertion_point(field_get:flare.rpc.SerializedServerPacket.using_raw_bytes)
  return using_raw_bytes_;
}
inline void SerializedServerPacket::set_using_raw_bytes(bool value) {
  
  using_raw_bytes_ = value;
  // @@protoc_insertion_point(field_set:flare.rpc.SerializedServerPacket.using_raw_bytes)
}

// bytes body = 3;
inline void SerializedServerPacket::clear_body() {
  body_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SerializedServerPacket::body() const {
  // @@protoc_insertion_point(field_get:flare.rpc.SerializedServerPacket.body)
  return body_.GetNoArena();
}
inline void SerializedServerPacket::set_body(const ::std::string& value) {
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:flare.rpc.SerializedServerPacket.body)
}
#if LANG_CXX11
inline void SerializedServerPacket::set_body(::std::string&& value) {
  
  body_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:flare.rpc.SerializedServerPacket.body)
}
#endif
inline void SerializedServerPacket::set_body(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:flare.rpc.SerializedServerPacket.body)
}
inline void SerializedServerPacket::set_body(const void* value, size_t size) {
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:flare.rpc.SerializedServerPacket.body)
}
inline ::std::string* SerializedServerPacket::mutable_body() {
  
  // @@protoc_insertion_point(field_mutable:flare.rpc.SerializedServerPacket.body)
  return body_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SerializedServerPacket::release_body() {
  // @@protoc_insertion_point(field_release:flare.rpc.SerializedServerPacket.body)
  
  return body_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SerializedServerPacket::set_allocated_body(::std::string* body) {
  if (body != NULL) {
    
  } else {
    
  }
  body_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), body);
  // @@protoc_insertion_point(field_set_allocated:flare.rpc.SerializedServerPacket.body)
}

// bytes attachment = 4;
inline void SerializedServerPacket::clear_attachment() {
  attachment_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SerializedServerPacket::attachment() const {
  // @@protoc_insertion_point(field_get:flare.rpc.SerializedServerPacket.attachment)
  return attachment_.GetNoArena();
}
inline void SerializedServerPacket::set_attachment(const ::std::string& value) {
  
  attachment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:flare.rpc.SerializedServerPacket.attachment)
}
#if LANG_CXX11
inline void SerializedServerPacket::set_attachment(::std::string&& value) {
  
  attachment_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:flare.rpc.SerializedServerPacket.attachment)
}
#endif
inline void SerializedServerPacket::set_attachment(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  attachment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:flare.rpc.SerializedServerPacket.attachment)
}
inline void SerializedServerPacket::set_attachment(const void* value, size_t size) {
  
  attachment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:flare.rpc.SerializedServerPacket.attachment)
}
inline ::std::string* SerializedServerPacket::mutable_attachment() {
  
  // @@protoc_insertion_point(field_mutable:flare.rpc.SerializedServerPacket.attachment)
  return attachment_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SerializedServerPacket::release_attachment() {
  // @@protoc_insertion_point(field_release:flare.rpc.SerializedServerPacket.attachment)
  
  return attachment_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SerializedServerPacket::set_allocated_attachment(::std::string* attachment) {
  if (attachment != NULL) {
    
  } else {
    
  }
  attachment_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), attachment);
  // @@protoc_insertion_point(field_set_allocated:flare.rpc.SerializedServerPacket.attachment)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace rpc
}  // namespace flare

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_flare_2frpc_2fprotocol_2fprotobuf_2fbinlog_2eproto__INCLUDED
